name: GitHub Snake

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run GitHub Snake
      - name: Run GitHub Snake
        uses: Platane/snk@v2.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          size: 12
          message: "Snake commit"

      # Step 3: Push the generated commits
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
